# .github/workflows/netlify.yml
name: Build & Deploy Web to Netlify
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Dependencies & Build root
        run: |
          npm ci && npm ci --prefix shared && npm ci --prefix web


      - name: Install Dependencies & Build web
        run: |
          npm run build --prefix web
        env:
          VITE_PSU_TOOLS_KEY: ${{ secrets.VITE_PSU_TOOLS_KEY }}

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './web/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          alias: deploy-preview-${{ github.event.number }}
          netlify-config-path: ./web/netlify.toml
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1

